packages:
    - "packages/core"
    - "packages/plugin-node"
    - "packages/plugin-goat"
    - "packages/plugin-solana-agentkit"
    - "packages/plugin-solana"
    - "packages/plugin-tee"
    - "packages/plugin-bootstrap"
    - "packages/plugin-twitter"
    - "packages/adapter-sqlite"
    - "!packages/adapter-pglite/**"
    - "!packages/adapter-postgres/**"
    - "!packages/adapter-redis/**"
    - "!packages/adapter-sqljs/**"
    - "!packages/adapter-supabase/**"
    - "!packages/client-farcaster/**"
    - "!packages/client-github/**"
    - "!packages/client-lens/**"
    - "!packages/client-slack/**"
    - "!packages/create-eliza-app/**"
    - "!packages/plugin-0g/**"
    - "!packages/plugin-3d-generation/**"
    - "!packages/plugin-abstract/**"
    - "!packages/plugin-allora/**"
    - "!packages/plugin-anyone/**"
    - "!packages/plugin-aptos/**"
    - "!packages/plugin-arthera/**"
    - "!packages/plugin-avail/**"
    - "!packages/plugin-avalanche/**"
    - "!packages/plugin-binance/**"
    - "!packages/plugin-coinbase/**"
    - "!packages/plugin-coinmarketcap/**"
    - "!packages/plugin-coingecko/**"
    - "!packages/plugin-autonome/**"
    - "!packages/plugin-coinprice/**"
    - "!packages/plugin-conflux/**"
    - "!packages/plugin-cosmos/**"
    - "!packages/plugin-cronoszkevm/**"
    - "!packages/plugin-depin/**"
    - "!packages/plugin-echochambers/**"
    - "!packages/plugin-evm/**"
    - "!packages/plugin-flow/**"
    - "!packages/plugin-fuel/**"
    - "!packages/plugin-genlayer/**"
    - "!packages/plugin-giphy/**"
    - "!packages/plugin-gitbook/**"
    - "!packages/plugin-goplus/**"
    - "!packages/plugin-icp/**"
    - "!packages/plugin-image-generation/**"
    - "!packages/plugin-rabbi-trader/**"
    - "!packages/plugin-defillama/**"
    - "!packages/plugin-intiface/**"
    - "!packages/plugin-letzai/**"
    - "!packages/plugin-movement/**"
    - "!packages/plugin-multiversx/**"
    - "!packages/plugin-near/**"
    - "!packages/plugin-nft-generation/**"
    - "!packages/plugin-obsidian/**"
    - "!packages/plugin-opacity/**"
    - "!packages/plugin-open-weather/**"
    - "!packages/plugin-spheron/**"
    - "!packages/plugin-spheron/**"
    - "!packages/plugin-stargaze/**"
    - "!packages/plugin-starknet/**"
    - "!packages/plugin-story/**"
    - "!packages/plugin-sui/**"
    - "!packages/plugin-tee-marlin/**"
    - "!packages/plugin-thirdweb/**"
    - "!packages/plugin-ton/**"
    - "!packages/plugin-video-generation/**"
    - "!packages/plugin-video-generation/**"
    - "!packages/plugin-web-search/**"
    - "!packages/plugin-whatsapp/**"
    - "!packages/plugin-zksync-era/**"
    - "docs"
    - "packages/*"
    - "client"
    - "agent"
#    - "!packages/plugin-trustdb/**" is needed by tee
